SELECT 
		CLI_NOME
FROM CLIENTE
JOIN FINANCIAMENTO ON FIN_CLI_ID = CLI_ID
JOIN TIPO_FINANCIAMENTO ON TPF_ID = FIN_TPF_ID
JOIN PAGAMENTO PAG ON PAG.PAG_FIN_ID = FIN_ID 
WHERE CLI_UF = 'SP'
AND PAG.PAG_DATA_PAGAMENTO IS NOT NULL
GROUP BY CLI_NOME, FIN_PARCELAS
HAVING COUNT(PAG.PAG_ID) >= (FIN_PARCELAS * 60 / 100);
