SELECT TOP 4
	CLI_NOME, 
	CLI_CELULAR 
FROM CLIENTE
JOIN FINANCIAMENTO ON FIN_CLI_ID = CLI_ID
JOIN TIPO_FINANCIAMENTO ON TPF_ID = FIN_TPF_ID
JOIN PAGAMENTO ON PAG_FIN_ID = FIN_ID 
WHERE PAG_DATA_PAGAMENTO IS NULL
AND DATEDIFF(DAY, PAG_DATA_VENCIMENTO, GETDATE()) >= 5
group by CLI_NOME, CLI_CELULAR