CREATE TABLE [dbo].[CLIENTE] (
    [CLI_ID]      INT           IDENTITY (1, 1) NOT NULL,
    [CLI_NOME]    VARCHAR (255) NOT NULL,
    [CLI_UF]      VARCHAR (2)   NOT NULL,
    [CLI_CELULAR] VARCHAR (16)  NOT NULL,
    CONSTRAINT [PK_CLIENTE] PRIMARY KEY CLUSTERED ([CLI_ID] ASC)
);

