CREATE TABLE [dbo].[FINANCIAMENTO] (
    [FIN_ID]              INT          IDENTITY (1, 1) NOT NULL,
    [FIN_CLI_ID]          INT          NOT NULL,
    [FIN_TPF_ID]          INT          NOT NULL,
    [FIN_VALOR_TOTAL]     DECIMAL (18) NOT NULL,
    [FIN_DATA_VENCIMENTO] DATE         NOT NULL,
    [FIN_PARCELAS]        INT          NOT NULL,
    CONSTRAINT [PK_FINANCIAMENTO] PRIMARY KEY CLUSTERED ([FIN_ID] ASC),
    CONSTRAINT [FK_CLI_FIN] FOREIGN KEY ([FIN_CLI_ID]) REFERENCES [dbo].[CLIENTE] ([CLI_ID]),
    CONSTRAINT [FK_TPF_FIN] FOREIGN KEY ([FIN_TPF_ID]) REFERENCES [dbo].[TIPO_FINANCIAMENTO] ([TPF_ID])
);



