CREATE TABLE [dbo].[PAGAMENTO] (
    [PAG_ID]              INT             IDENTITY (1, 1) NOT NULL,
    [PAG_FIN_ID]          INT             NOT NULL,
    [PAG_NUM_PARCELA]     INT             NOT NULL,
    [PAG_VALOR_PAGO]      DECIMAL (18, 2) NULL,
    [PAG_DATA_VENCIMENTO] DATE            NOT NULL,
    [PAG_DATA_PAGAMENTO]  DATETIME        NULL,
    CONSTRAINT [PK_PAGAMENTO] PRIMARY KEY CLUSTERED ([PAG_ID] ASC),
    CONSTRAINT [FK_FIN_PAG] FOREIGN KEY ([PAG_FIN_ID]) REFERENCES [dbo].[FINANCIAMENTO] ([FIN_ID])
);



