CREATE TABLE [dbo].[TIPO_FINANCIAMENTO] (
    [TPF_ID]        INT           IDENTITY (1, 1) NOT NULL,
    [TPF_DESCRICAO] VARCHAR (255) NOT NULL,
    CONSTRAINT [PK_TIPO_FINANCIAMENTO] PRIMARY KEY CLUSTERED ([TPF_ID] ASC)
);

